[variables]
NIXPACKS_PHP_VERSION = "8.3"
NODE_ENV = "production"
APP_ENV = "production"
ASSET_URL = ""

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "php --version",
  "node --version",
  "npm --version",
  "composer install --optimize-autoloader --no-dev --no-scripts --no-interaction",
  "npm ci"
]

[phases.build]
cmds = [
  "echo 'Building frontend assets...'",
  "if [ ! -d 'public/build' ]; then npm run build; else echo 'Using committed build assets'; fi",
  "echo 'Laravel optimizations...'",
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache",
  "php artisan optimize",
  "echo 'Performance optimizations complete'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"