[variables]
NIXPACKS_PHP_VERSION = "8.3"
NODE_ENV = "production"
APP_ENV = "production"
ASSET_URL = ""

[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "php --version",
  "node --version",
  "npm --version",
  "composer install --optimize-autoloader --no-dev --no-scripts --no-interaction",
  "npm ci"
]

[phases.build]
cmds = [
  "echo 'Checking for existing build assets...'",
  "ls -la public/build/ || echo 'No existing build directory'",
  "if [ ! -d 'public/build' ]; then echo 'Building frontend assets...'; ls -la package.json vite.config.js tailwind.config.js resources/css/app.css; npm run build; else echo 'Using committed build assets'; fi",
  "echo 'Final asset check...'",
  "ls -la public/build/",
  "ls -la public/build/assets/",
  "echo 'CSS file size:'",
  "wc -c public/build/assets/*.css",
  "echo 'Laravel optimizations...'",
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
